### ISSUE TITLE
Possible Light Gallery plugin issue with version 2.0.0-alpha

### ISSUE THREAD

**Issue by jaques** [thumbsup/node-thumbsup#53]
Hello,

I recently installed thumbsup 2.0.0-alpha from NPM.  It works great, and does exactly what I need. I noticed that videos don't seem to work though.

A quick check and it looks like it's unable to find the light gallery plugins (video, autoplay, pager etc.) as they don't seem to be in the public/light-gallery/js folder.

Could it be that I've done something wrong?

Thanks,
Richard.

**Comment by rprieto** [comment]
Hi @jaques, thanks for finding this! It was an issue upgrading to the latest version of `lightgallery`. The version I used before bundled all the plugins, but now it looks like they need to be downloaded separately.

I'll publish a new `alpha` version soon, otherwise feel free to test on `HEAD` and let me know if it works.

**Comment by jaques** [comment]
This worked a treat.  Thank you.  I managed to get it all working with your lambda-cloudfront-cookies & login page as well.

Thank you for this, great stuff.

**Comment by rprieto** [comment]
Wow that's great news! Can you let me know if you see anything that should be fixed before releasing `v2.0.0`?
